//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.ServicoConcessionaria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoConcessionaria.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertFabricante", ReplyAction="http://tempuri.org/IService1/InsertFabricanteResponse")]
        void InsertFabricante(Modelo.Fabricante f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertFabricante", ReplyAction="http://tempuri.org/IService1/InsertFabricanteResponse")]
        System.Threading.Tasks.Task InsertFabricanteAsync(Modelo.Fabricante f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectFabricantes", ReplyAction="http://tempuri.org/IService1/SelectFabricantesResponse")]
        Modelo.Fabricante[] SelectFabricantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectFabricantes", ReplyAction="http://tempuri.org/IService1/SelectFabricantesResponse")]
        System.Threading.Tasks.Task<Modelo.Fabricante[]> SelectFabricantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateFabricante", ReplyAction="http://tempuri.org/IService1/UpdateFabricanteResponse")]
        void UpdateFabricante(Modelo.Fabricante f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateFabricante", ReplyAction="http://tempuri.org/IService1/UpdateFabricanteResponse")]
        System.Threading.Tasks.Task UpdateFabricanteAsync(Modelo.Fabricante f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFabricante", ReplyAction="http://tempuri.org/IService1/DeleteFabricanteResponse")]
        void DeleteFabricante(Modelo.Fabricante f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFabricante", ReplyAction="http://tempuri.org/IService1/DeleteFabricanteResponse")]
        System.Threading.Tasks.Task DeleteFabricanteAsync(Modelo.Fabricante f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertVeiculo", ReplyAction="http://tempuri.org/IService1/InsertVeiculoResponse")]
        void InsertVeiculo(Modelo.Veiculo v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertVeiculo", ReplyAction="http://tempuri.org/IService1/InsertVeiculoResponse")]
        System.Threading.Tasks.Task InsertVeiculoAsync(Modelo.Veiculo v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectVeiculos", ReplyAction="http://tempuri.org/IService1/SelectVeiculosResponse")]
        Modelo.Veiculo[] SelectVeiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectVeiculos", ReplyAction="http://tempuri.org/IService1/SelectVeiculosResponse")]
        System.Threading.Tasks.Task<Modelo.Veiculo[]> SelectVeiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectVeiculosDisponiveis", ReplyAction="http://tempuri.org/IService1/SelectVeiculosDisponiveisResponse")]
        Modelo.Veiculo[] SelectVeiculosDisponiveis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectVeiculosDisponiveis", ReplyAction="http://tempuri.org/IService1/SelectVeiculosDisponiveisResponse")]
        System.Threading.Tasks.Task<Modelo.Veiculo[]> SelectVeiculosDisponiveisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectVeiculosVendidos", ReplyAction="http://tempuri.org/IService1/SelectVeiculosVendidosResponse")]
        Modelo.Veiculo[] SelectVeiculosVendidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectVeiculosVendidos", ReplyAction="http://tempuri.org/IService1/SelectVeiculosVendidosResponse")]
        System.Threading.Tasks.Task<Modelo.Veiculo[]> SelectVeiculosVendidosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateVeiculo", ReplyAction="http://tempuri.org/IService1/UpdateVeiculoResponse")]
        void UpdateVeiculo(Modelo.Veiculo v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateVeiculo", ReplyAction="http://tempuri.org/IService1/UpdateVeiculoResponse")]
        System.Threading.Tasks.Task UpdateVeiculoAsync(Modelo.Veiculo v);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Negocio.ServicoConcessionaria.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Negocio.ServicoConcessionaria.IService1>, Negocio.ServicoConcessionaria.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertFabricante(Modelo.Fabricante f) {
            base.Channel.InsertFabricante(f);
        }
        
        public System.Threading.Tasks.Task InsertFabricanteAsync(Modelo.Fabricante f) {
            return base.Channel.InsertFabricanteAsync(f);
        }
        
        public Modelo.Fabricante[] SelectFabricantes() {
            return base.Channel.SelectFabricantes();
        }
        
        public System.Threading.Tasks.Task<Modelo.Fabricante[]> SelectFabricantesAsync() {
            return base.Channel.SelectFabricantesAsync();
        }
        
        public void UpdateFabricante(Modelo.Fabricante f) {
            base.Channel.UpdateFabricante(f);
        }
        
        public System.Threading.Tasks.Task UpdateFabricanteAsync(Modelo.Fabricante f) {
            return base.Channel.UpdateFabricanteAsync(f);
        }
        
        public void DeleteFabricante(Modelo.Fabricante f) {
            base.Channel.DeleteFabricante(f);
        }
        
        public System.Threading.Tasks.Task DeleteFabricanteAsync(Modelo.Fabricante f) {
            return base.Channel.DeleteFabricanteAsync(f);
        }
        
        public void InsertVeiculo(Modelo.Veiculo v) {
            base.Channel.InsertVeiculo(v);
        }
        
        public System.Threading.Tasks.Task InsertVeiculoAsync(Modelo.Veiculo v) {
            return base.Channel.InsertVeiculoAsync(v);
        }
        
        public Modelo.Veiculo[] SelectVeiculos() {
            return base.Channel.SelectVeiculos();
        }
        
        public System.Threading.Tasks.Task<Modelo.Veiculo[]> SelectVeiculosAsync() {
            return base.Channel.SelectVeiculosAsync();
        }
        
        public Modelo.Veiculo[] SelectVeiculosDisponiveis() {
            return base.Channel.SelectVeiculosDisponiveis();
        }
        
        public System.Threading.Tasks.Task<Modelo.Veiculo[]> SelectVeiculosDisponiveisAsync() {
            return base.Channel.SelectVeiculosDisponiveisAsync();
        }
        
        public Modelo.Veiculo[] SelectVeiculosVendidos() {
            return base.Channel.SelectVeiculosVendidos();
        }
        
        public System.Threading.Tasks.Task<Modelo.Veiculo[]> SelectVeiculosVendidosAsync() {
            return base.Channel.SelectVeiculosVendidosAsync();
        }
        
        public void UpdateVeiculo(Modelo.Veiculo v) {
            base.Channel.UpdateVeiculo(v);
        }
        
        public System.Threading.Tasks.Task UpdateVeiculoAsync(Modelo.Veiculo v) {
            return base.Channel.UpdateVeiculoAsync(v);
        }
    }
}
